import MatchCard from '../Components/MatchCard';

function CurrentPage() {
    const data = [
        {title: "Europe Friend", 
        team_a: "SLOVAN LIBEREC", 
        awayTeamScore: 1, 
        awayTeamNum: 75, 
        team_b: "MIEDZ", 
        score: "2:0",
        goal: false,
        sport_category_name: "USA",
        sport_tournament_name: "US-league",
      },
      {title: "Europe Friend", 
      team_a: "SLOVAN LIBEREC", 
      awayTeamScore: 1, 
      awayTeamNum: 15, 
      team_b: "MIEDZ", 
      score: "2:0",
      goal: false,
      sport_category_name: "USA",
      sport_tournament_name: "US-league",
    },
    {title: "Europe Friend", 
    team_a: "SLOVAN LIBEREC", 
    awayTeamScore: 1, 
    awayTeamNum: 15, 
    team_b: "MIEDZ", 
    score: "2:0",
    goal: true,
    sport_category_name: "USA",
    sport_tournament_name: "US-league",
  },
  {title: "Europe Friend", 
        team_a: "SLOVAN LIBEREC", 
        awayTeamScore: 1, 
        awayTeamNum: 65, 
        team_b: "MIEDZ", 
        score: "2:0",
        goal: false,
        sport_category_name: "USA",
        sport_tournament_name: "US-league",
      },
      {title: "Europe Friend", 
        team_a: "SLOVAN LIBEREC", 
        awayTeamScore: 1, 
        awayTeamNum: 70, 
        team_b: "MIEDZ", 
        score: "2:0",
        goal: false,
        sport_category_name: "USA",
        sport_tournament_name: "US-league",
      },
      {title: "Europe Friend", 
        team_a: "SLOVAN LIBEREC", 
        awayTeamScore: 1, 
        awayTeamNum: 40, 
        team_b: "MIEDZ", 
        score: "2:0",
        goal: false,
        sport_category_name: "USA",
        sport_tournament_name: "US-league",
      },
      {title: "Europe Friend", 
        team_a: "SLOVAN LIBEREC", 
        awayTeamScore: 1, 
        awayTeamNum: 40, 
        team_b: "MIEDZ", 
        score: "2:0",
        goal: false,
        sport_category_name: "USA",
        sport_tournament_name: "US-league",
      },
      {title: "Europe Friend", 
        team_a: "SLOVAN LIBEREC", 
        awayTeamScore: 1, 
        awayTeamNum: 40, 
        team_b: "MIEDZ", 
        score: "2:0",
        goal: false,
        sport_category_name: "USA",
        sport_tournament_name: "US-league",
      },
      {title: "Europe Friend", 
        team_a: "SLOVAN LIBEREC", 
        awayTeamScore: 1, 
        awayTeamNum: 40, 
        team_b: "MIEDZ", 
        score: "2:0",
        goal: false,
        sport_category_name: "USA",
        sport_tournament_name: "US-league",
      },
      {title: "Europe Friend", 
        team_a: "SLOVAN LIBEREC", 
        awayTeamScore: 1, 
        awayTeamNum: 40, 
        team_b: "MIEDZ", 
        score: "2:0",
        goal: false,
        sport_category_name: "USA",
        sport_tournament_name: "US-league",
      },
      {title: "Europe Friend", 
      team_a: "SLOVAN LIBEREC", 
      awayTeamScore: 1, 
      awayTeamNum: 40, 
      team_b: "MIEDZ", 
      score: "2:0",
      goal: false,
      sport_category_name: "USA",
      sport_tournament_name: "US-league",
    },
    {title: "Europe Friend", 
      team_a: "USA ", 
      awayTeamScore: 1, 
      awayTeamNum: 40, 
      team_b: "MIEDZ", 
      score: "2:0",
      goal: false,
      sport_category_name: "USA",
      sport_tournament_name: "US-league",
    },
    {title: "Europe Friend", 
      team_a: "SLOVAN LIBEREC", 
      awayTeamScore: 1, 
      awayTeamNum: 40, 
      team_b: "MIEDZ", 
      score: "2:0",
      goal: false,
      sport_category_name: "USA",
      sport_tournament_name: "US-league",
    },
    {title: "USA Friend", 
    team_a: "SLOVAN LIBEREC", 
    awayTeamScore: 1, 
    awayTeamNum: 40, 
    team_b: "MIEDZ", 
    score: "2:0",
    goal: false,
    sport_category_name: "USA",
    sport_tournament_name: "US-league",
  },
  {title: "Europe Friend", 
    team_a: "AFRICAN LIBEREC", 
    awayTeamScore: 1, 
    awayTeamNum: 40, 
    team_b: "MIEDZ", 
    score: "2:0",
    goal: true,
    sport_category_name: "USA",
    sport_tournament_name: "US-league",
  },
  {title: "Europe Friend", 
    team_a: "SLOVAN LIBEREC", 
    awayTeamScore: 1, 
    awayTeamNum: 40, 
    team_b: "MIEDZ", 
    score: "2:0",
    goal: true,
    sport_category_name: "USA",
    sport_tournament_name: "US-league",
  },
      ]
  return (
    <div className="">
      <div className='bg-[#E5E5E5] w-[100%]'>
        <MatchCard details={data}/>
      </div>
    </div>
  );
}

export default CurrentPage;
